CREATE DATABASE oAuth_Google;
USE oAUTH_Google;

CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    googleId VARCHAR(512) UNIQUE NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL,
    username VARCHAR(255) NOT NULL,
    userImage TEXT NOT NULL,
    refreshToken TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blogs (
    id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    thumbnail TEXT NOT NULL,
    author_googleId VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (author_googleId) REFERENCES users(googleId) ON DELETE CASCADE
);

CREATE TABLE blog_reactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    blog_id INT NOT NULL,
    user_googleId VARCHAR(512) NOT NULL,
    reaction ENUM('like','dislike') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_blog_user (blog_id, user_googleId),
    FOREIGN KEY (blog_id) REFERENCES blogs(id) ON DELETE CASCADE,
    FOREIGN KEY (user_googleId) REFERENCES users(googleId) ON DELETE CASCADE
);